language: ruby
rvm:
 - 2.6.3
before_script:
   - RAILS_ENV=development bundle exec rails webpacker:compile
   - bundle exec rake db:drop
   - bundle exec rake db:migrate --trace
   - bundle exec rake db:development:prepare
script:
   - bin/rails test
before_install:
    - gem update --system
    - gem install bundler
