language: ruby
rvm:
 - 2.6.3
before_script:
   - yarn install --check-files
   - bundle exec rake db:drop
   - RAILS_ENV=development bundle exec rake db:migrate --trace
   - bundle exec rake db:test:prepare
script:
   - bin/rails test
before_install:
    - gem update bundler
    - gem update --system
    - gem install bundler
