defaults: &defaults
  name: Vortrics
  :performance:
    :graph_limit: 60
  :jira:
    :agile_url: /rest/agile/1.0
    :green_hopper_url: /rest/greenhopper/1.0
    :fields: key,priority,issuetype,status,componentes,customfield_11382,summary,customfield_11802,timeoriginalestimate,components,description,assignee,created,updated,resolutiondate,closedSprints,sprint,histories
    :changelogfields: status,flagged,component,resolution,epic link
  :changelog:
    :flagged: impediment
    :open: open,nil,to do
    :backlog: backlog,ready
    :wip: in progress,analysis
    :testing: review,in review,testing
    :done: closed,done,production
  :baseline:
    :leadtime: 10
    :cycletime: 1
  :advices:
    :more_than_one_sprint?:
      :advice_type: :more_than_one_sprint?
      :subject: Kaizen
      :completed: false
      :read: false
      :description: "<strong>Listen up!</strong> Sprint has stories that started <strong>sprints ago</strong>, bring them at the retrospective and seek for improvements to avoid this situation."
    :estimation_over_average_closed_points?:
      :advice_type: :estimation_over_average_closed_points?
      :subject: Kaizen
      :completed: false
      :read: false
      :description: "<strong>Ups!</strong> Sprint has stories which estimation is bigger than <strong>15%</strong> of team's capacity. Reduce either complexity by splitting or risk."
    :overcommitment?:
      :advice_type: :overcommitment?
      :subject: Kaizen
      :completed: false
      :read: false
      :description: "<strong>Watch out!</strong> Sprint commitment is bigger than historical average, there is a strong possibility of leftovers at the end."
    :has_service_types?:
      :advice_type: :has_service_types?
      :subject: Kaizen
      :completed: false
      :read: false
      :description: "<strong>Advice</strong> The Sprint has more than one service type, see if having different work-flows and policies may help improving the lead time."
    :variance_volatility?:
      :advice_type: :variance_volatility?
      :subject: Kaizen
      :completed: false
      :read: false
      :description: "<strong>Ups!</strong> Team's velocity seems highly spread out from its average value. Ideally, teams should display a fairly consistent velocity, ideally with a gradually increasing slope. Major gaps and spikes in velocity are not a good sign."
  :messages:
    :external_service_error: "Unable to retrieve external service information. Please try it later."
    :no_teams_available: "Before getting information from the external service, create a team."
    :first_steps: "<h4>Welcome to Vortrics</h4><strong>Hands up!</strong> These are the first steps to be followed before getting data from JIRA
    <br>
    <ul>
    <li>Create an external service connection towards your JIRA service, we strongly recommend OAuth rather than a Basic authentication. </li>
    <li>Import team(s) from the external service</li>
    <li>Add sprint(s) or task(s) from the external service and start enjoying metrics and charts.</li>
    </ul>"
  :popover:
    :average_velocity: "Velocity is quite simple to calculate. At the end of a sprint, add up the total of all the story points that were moved to 'Done' (based on your Definition of Done) in that sprint."
    :average_stories: "At the end of a sprint, add up the total of all the user stories that were moved to 'Done' (based on your Definition of Done) in that sprint."
    :varianza: "It measures how far a set of sprint story counting numbers are spread out from their average value."
    :sprint_forecast: "Forecast team's velocity according to current team work-force. Ideally, you should not commit the same amount of work if there are less people working."
    :pass_rate: "Quality metric, it is the percentage of 'Review' that pass the first time they are run. If it is below 90%, there is a quality problem, find out the part of the process that is a cause of problems."
    :bug_sprint: "This is a simple metric that lets you see how many defects you are raising each sprint. You calculate by adding the number of defects that were created at some point during the sprint."
    :ratio_bugs: "It is the ratio of the defects created during the sprint to the total number of user stories in the sprint."
    :time_blocked: "Simply, Adds up all the time that any story or task in the current sprint spent in a blocked state."
    :ratio_time_blocked: "It tells you how much time every story in the current sprint would spend blocked, distributing total blocked time per user story or task."
    :ratio_items_blocked: "Measures what proportion of user stories in a sprint are blocked by impediments."
    :scope_change: "It shows how much changes has suffered the original sprint commitment. "


development:
  <<: *defaults
  name: Vortrics Development

production:
  <<: *defaults
  name: Vortrics
  :jira:
    :fields: key,priority,issuetype,status,componentes,customfield_11382,summary,customfield_11802,timeoriginalestimate,components,description,assignee,created,updated,resolutiondate,closedSprints,sprint,histories
    :changelogfields: status,flagged,component,resolution,epic link



test: &test
  <<: *defaults
  name: Vortrics Testing