require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe AdvicesController, type: :controller do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # Advice. As you add validations to Advice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {advice_type: "test",subject: "test",description: "test",read: false,completed: false}
  }

  let(:invalid_attributes) {
    {advice_hacking: "test",subject: "test",description: "test",read: false,completed: false}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      advice = FactoryBot.create(:advice)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  # describe "GET #show" do
  #   it "returns a success response" do
  #     advice = FactoryBot.create(:advice)
  #     get :show, params: {id: advice.to_param}, session: valid_session
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET #edit" do
  #   it "returns a success response" do
  #     advice = FactoryBot.create(:advice)
  #     get :edit, params: {id: advice.to_param}, session: valid_session
  #     expect(response).to be_successful
  #   end
  # end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Advice" do
        expect {
          post :create, params: {advice: valid_attributes}, session: valid_session
        }.to change(Advice, :count).by(1)
      end

      it "redirects to the created advice" do
        post :create, params: {advice: valid_attributes}, session: valid_session
        expect(response).to redirect_to advices_path
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {advice: invalid_attributes}, session: valid_session
        expect(response).to redirect_to advices_path
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {advice_type: "test",subject: "test",description: "test",read: true,completed: false}
      }

      it "updates the requested advice" do
        advice = FactoryBot.create(:advice)
        put :update, params: {id: advice.to_param, advice: new_attributes}, session: valid_session
        advice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the advice" do
        advice = FactoryBot.create(:advice)
        put :update, params: {id: advice.to_param, advice: valid_attributes}, session: valid_session
        expect(response).to redirect_to(advice)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        advice = FactoryBot.create(:advice)
        put :update, params: {id: advice.to_param, advice: invalid_attributes}, session: valid_session
        puts response.to_s
        expect(response).to have_http_status(302)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested advice" do
      advice = Advice.create! valid_attributes
      expect {
        delete :destroy, params: {id: advice.to_param}, session: valid_session
      }.to change(Advice, :count).by(-1)
    end

    it "redirects to the advices list" do
      advice = FactoryBot.create(:advice)
      delete :destroy, params: {id: advice.to_param}
      expect(response).to redirect_to(advices_url)
    end
  end

end
